# dockerfile for image_back:v7.0 

# Stage 1 - BUILD
FROM alpine:3.17 AS build-step
RUN apk add --no-cache git maven && \
    git clone https://github.com/WalfroyB/TLC_PROJET_BOUTIN.git && \
    rm -rf TLC_PROJECT_BOUTIN/front
WORKDIR /TLC_PROJET_BOUTIN/api
RUN mvn clean package -Dquarkus.package.type=uber-jar

# Stage 2 - RUN
FROM alpine:3.17 AS prod
RUN apk add --no-cache openjdk11
WORKDIR /app
COPY --from=build-step /TLC_PROJET_BOUTIN/api/target/tlcdemoApp-1.0.0-SNAPSHOT-runner.jar /app/
CMD ["java", "-jar", "tlcdemoApp-1.0.0-SNAPSHOT-runner.jar"]

CMD [ "/deployments/run-java.sh" ]
